[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.1"
  HUGO_ENV = "production"

# Add this section for Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# This is often also required for Netlify Identity
[[redirects]]
  from = "/.netlify/identity"
  to = "/.netlify/identity/index.html"
  status = 200
