[build]
  publish = "."

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog/"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/post.html?slug=:slug"
  status = 200