[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.1"
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin"
  to = "/admin/cms.html"
  status = 200
