[[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.1"
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity"
  to = "/.netlify/identity/index.html"
  status = 200

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/plain"
