[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.1"
  HUGO_ENV = "production"

# Redirect all /admin routes to the CMS index.html
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Serve config.yml correctly
[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"
