backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "booknotes"
    label: "Booknotes"
    folder: "content/booknotes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "digital"
    label: "Digital"
    folder: "content/digital"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "podcast"
    label: "Podcast"
    folder: "content/podcast"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "quotes"
    label: "Quotes"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "lenscape"
    label: "Lenscape"
    folder: "content/lenscape"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "bio"
    label: "Bio"
    folder: "content/bio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "quiz"
    label: "Quiz"
    folder: "content/quiz"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Question", name: "question", widget: "text"}
      - {label: "Option A", name: "option_a", widget: "string"}
      - {label: "Option B", name: "option_b", widget: "string"}
      - {label: "Option C", name: "option_c", widget: "string"}
      - {label: "Option D", name: "option_d", widget: "string"}
      - {label: "Correct Answer", name: "correct_answer", widget: "select", options: ["A", "B", "C", "D"]}
      - {label: "Explanation", name: "explanation", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
