# ==================================================
# NETLIFY CMS CONFIGURATION
# ==================================================

# Backend Configuration
backend:
  name: git-gateway
  branch: dev  # Development branch for commits from CMS

publish_mode: editorial_workflow

# Media Configuration
media_folder: "assets/images"
public_folder: "/assets/images"

# Site URL
site_url: https://moileon.in

# ==================================================
# CONTENT COLLECTIONS
# ==================================================

collections:

  # ------------------------------
  # QUIZ QUESTIONS
  # ------------------------------
  - name: "quiz"
    label: "Quiz Questions"
    folder: "content/quiz"
    create: true
    identifier_field: question
    summary: "{{question}}"
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - label: "Question"
        name: "question"
        widget: "text"
        hint: "Main quiz question"
      - label: "Correct Answer"
        name: "correct_answer"
        widget: "text"
      - label: "Alternative Answers"
        name: "alternative_answers"
        widget: "list"
        required: false
      - label: "Explanation"
        name: "explanation"
        widget: "markdown"
        required: false
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Learning"
          - "Philosophy"
          - "Yoga"
          - "Life Skills"
          - "Knowledge"
          - "Wisdom"
        default: "Learning"
      - label: "Difficulty Level"
        name: "difficulty"
        widget: "select"
        options:
          - "Beginner"
          - "Intermediate"
          - "Advanced"
        default: "Beginner"
      - label: "Date Created"
        name: "date"
        widget: "datetime"
      - label: "Active"
        name: "active"
        widget: "boolean"
        default: true
      - label: "Points"
        name: "points"
        widget: "number"
        default: 10

  # ------------------------------
  # BLOG POSTS
  # ------------------------------
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Custom URL"
        name: "custom_url"
        widget: "string"
        required: false
        hint: "Optional: Custom URL path (e.g., 'my-special-post'). Leave blank to auto-generate from title."
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Content"
        name: "body"
        widget: "markdown"

  # ------------------------------
  # BOOK NOTES
  # ------------------------------
  - name: "booknotes"
    label: "Book Notes"
    folder: "content/booknotes"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Book Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "book_author"
        widget: "string"
      - label: "Date Added"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Book Cover"
        name: "book_cover"
        widget: "image"
        required: false
      - label: "Rating"
        name: "rating"
        widget: "select"
        options: ["1", "2", "3", "4", "5"]
        required: false
      - label: "Key Takeaways"
        name: "key_takeaways"
        widget: "list"
        field:
          label: "Takeaway"
          name: "takeaway"
          widget: "string"
      - label: "Notes"
        name: "body"
        widget: "markdown"

  # ------------------------------
  # PROJECTS
  # ------------------------------
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Project Name"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Status"
        name: "status"
        widget: "select"
        options:
          - "Active"
          - "Completed"
          - "On Hold"
          - "Planned"
      - label: "Project Type"
        name: "project_type"
        widget: "select"
        options:
          - "Web Development"
          - "Mobile App"
          - "Research"
          - "Writing"
          - "Other"
      - label: "Technologies Used"
        name: "technologies"
        widget: "list"
        required: false
      - label: "Project URL"
        name: "project_url"
        widget: "string"
        required: false
      - label: "GitHub Repository"
        name: "github_url"
        widget: "string"
        required: false
      - label: "Project Image"
        name: "project_image"
        widget: "image"
        required: false
      - label: "Description"
        name: "body"
        widget: "markdown"

  # ------------------------------
  # QUOTES
  # ------------------------------
  - name: "quotes"
    label: "Quotes"
    folder: "content/quotes"
    create: true
    identifier_field: quote
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - label: "Quote"
        name: "quote"
        widget: "text"
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Date Added"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Wisdom"
          - "Motivation"
          - "Philosophy"
          - "Yoga"
          - "Life"
          - "Success"
        required: false
      - label: "Personal Note"
        name: "note"
        widget: "text"
        required: false

  # ------------------------------
  # SITE SETTINGS
  # ------------------------------
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "content/settings/navigation.md"
        fields:
          - label: "Navigation Items"
            name: "nav_items"
            widget: "list"
            fields:
              - label: "Label"
                name: "label"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Open in New Tab"
                name: "external"
                widget: "boolean"
                default: false

      - label: "Social Media"
        name: "social"
        file: "content/settings/social.md"
        fields:
          - label: "LinkedIn URL"
            name: "linkedin"
            widget: "string"
            default: "https://www.linkedin.com/in/leonkaushik"
          - label: "Twitter/X URL"
            name: "twitter"
            widget: "string"
            default: "https://x.com/iobyleon"
          - label: "GitHub URL"
            name: "github"
            widget: "string"
            required: false
          - label: "Email"
            name: "email"
            widget: "string"
            required: false

      - label: "Quiz Settings"
        name: "quiz_settings"
        file: "content/settings/quiz.md"
        fields:
          - label: "Quiz Title"
            name: "quiz_title"
            widget: "string"
            default: "Quest On!"
          - label: "Show Random Questions"
            name: "random_questions"
            widget: "boolean"
            default: true
          - label: "Questions Per Session"
            name: "questions_per_session"
            widget: "number"
            default: 1
          - label: "Show Explanations"
            name: "show_explanations"
            widget: "boolean"
            default: true
          - label: "Enable Scoring"
            name: "enable_scoring"
            widget: "boolean"
            default: true

      - label: "Site Images"
        name: "images"
        file: "content/assets/images/lotus.png"
        fields:
          - label: "Lotus Image"
            name: "lotus_image"
            widget: "image"
            hint: "Upload the main lotus image for the homepage"
